# Set theme
remote_theme: daviddarnes/alembic

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-default-layout
- jekyll-feed
- jemoji
- jekyll-remote-theme

markdown: kramdown
kramdown:
  math_engine: mathjax
# Site settings
url: 'https://mydomain.com'
baseurl: ''
title: 'Veridolu'
description: 'Colorful plots are maintained here.'
permalink: pretty
logo: "https://i.ibb.co/fxJzqqW/Screen-Shot-2019-08-23-at-22-01-21.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Blog
  url: /blog/

# Footer nav
navigation_footer:
- title: Back to Home
  url: "./#top"

# Collections
collections:
  posts:
    title: Posts
    output: true
    feature_text: |
     ## <mark style="background-color:#202A4F; color:white">Colorful plots are maintained here.</mark>
    feature_image: "https://i.ibb.co/ws9HtBQ/tile.jpg"
